import json
import glob
import os
from pathlib import Path
from datetime import datetime

def get_latest_classified_file(search_dir: str) -> str:
    """
    Finds the most recently created JSON file in the specified directory.
    """
    # Create pattern to look for all .json files in the directory
    pattern = os.path.join(search_dir, "*.json")
    list_of_files = glob.glob(pattern)
    
    if not list_of_files:
        raise FileNotFoundError(f"No JSON files found in directory: {search_dir}")
    
    # Return the file with the latest creation/modification time
    return max(list_of_files, key=os.path.getmtime)

def save_classification_summary(json_file_path: str, output_folder: str = "daily_summaries") -> str:
    """
    Reads the classification JSON and saves a formatted text summary to a folder.
    """
    folder = Path(output_folder)
    folder.mkdir(parents=True, exist_ok=True)
    
    try:
        with open(json_file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        return f"Error reading file: {e}"

    date_str = datetime.now().strftime("%Y-%m-%d")
    high, medium, low_count = [], [], 0

    for entry in data.values():
        impact = entry.get("classification", {}).get("impact", "low").lower()
        desc = entry.get("classification", {}).get("description", "No description.")
        
        field = entry.get("field", "")
        before = entry.get("before", "")
        after = entry.get("after", "")
        
        detail = ""
        if field and before and after and "url" not in field.lower():
            label = field.replace('_', ' ').capitalize()
            detail = f"\n    {label}: {before}  →  {after}"

        item_str = f" • {desc}{detail}"

        if impact == "high":
            high.append(item_str)
        elif impact == "medium":
            medium.append(item_str)
        else:
            low_count += 1

    content = [
        f"ING Market Watch Summary — {date_str}",
        f"{len(high)} urgent · {len(medium)} to monitor · {low_count} low",
        "-" * 50,
        "\n🔴 REQUIRES ATTENTION"
    ]
    content.extend(high if high else [" • No urgent changes today."])
    content.append("\n🟡 MONITOR")
    content.extend(medium if medium else [" • No items to monitor today."])
    content.extend([
        f"\n🟢 LOW IMPACT: {low_count} minor changes.",
        "\n👉 Full dashboard: https://ing-market-watch.streamlit.app",
        "-" * 50,
        "Generated by ING Market Watch Bot"
    ])

    file_path = folder / f"Summary_{date_str}.txt"
    with open(file_path, "w", encoding="utf-8") as f:
        f.write("\n".join(content))
    
    return f"✅ Success! Summary saved to: {file_path}"