import json
import glob
import os
from pathlib import Path
from datetime import datetime
import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def get_latest_classified_file(search_dir: str) -> str:
    """
    Finds the most recently created JSON file in the specified directory.
    """
    # Create pattern to look for all .json files in the directory
    pattern = os.path.join(search_dir, "*.json")
    list_of_files = glob.glob(pattern)
    
    if not list_of_files:
        raise FileNotFoundError(f"No JSON files found in directory: {search_dir}")
    
    # Return the file with the latest creation/modification time
    return max(list_of_files, key=os.path.getmtime)

def save_classification_summary(json_file_path: str, output_folder: str = "daily_summaries") -> str:
    """
    Reads the classification JSON and saves a formatted text summary to a folder.
    """
    folder = Path(output_folder)
    folder.mkdir(parents=True, exist_ok=True)
    
    try:
        with open(json_file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        return f"Error reading file: {e}"

    date_str = datetime.now().strftime("%Y-%m-%d")
    high, medium, low_count = [], [], 0

    for entry in data.values():
        impact = entry.get("classification", {}).get("impact", "low").lower()
        desc = entry.get("classification", {}).get("description", "No description.")
        
        field = entry.get("field", "")
        before = entry.get("before", "")
        after = entry.get("after", "")
        
        detail = ""
        if field and before and after and "url" not in field.lower():
            label = field.replace('_', ' ').capitalize()
            detail = f"\n    {label}: {before}  →  {after}"

        item_str = f" • {desc}{detail}"

        if impact == "high":
            high.append(item_str)
        elif impact == "medium":
            medium.append(item_str)
        else:
            low_count += 1

    content = [
        f"ING Market Watch Summary — {date_str}",
        f"{len(high)} urgent · {len(medium)} to monitor · {low_count} low",
        "-" * 50,
        "\n🔴 REQUIRES ATTENTION"
    ]
    content.extend(high if high else [" • No urgent changes today."])
    content.append("\n🟡 MONITOR")
    content.extend(medium if medium else [" • No items to monitor today."])
    content.extend([
        f"\n🟢 LOW IMPACT: {low_count} minor changes.",
        "\n👉 Full dashboard: https://ing-market-watch.streamlit.app",
        "-" * 50,
        "Generated by ING Market Watch Bot"
    ])

    file_path = folder / f"Summary_{date_str}.txt"
    with open(file_path, "w", encoding="utf-8") as f:
        f.write("\n".join(content))
    
    return str(file_path)

def send_summary_email(txt_file_path: str, recipients: list[str], sender: str, password: str) -> str:
    """
    RECEIVES sender and password as direct strings.
    """
    # Double check if they arrived empty
    if not sender:
        return "❌ Error: Sender email is empty."
    if not password:
        return "❌ Error: Password is empty."
    """
    Reads a text file and sends its content. 
    Credentials are passed directly to avoid environment scope issues.
    """
    if not sender or not password:
        return "❌ Error: Credentials were not passed to the function."

    try:
        with open(txt_file_path, 'r', encoding='utf-8') as f:
            body = f.read()
    except Exception as e:
        return f"❌ Error reading TXT file: {e}"
    
    # 1. Get credentials from environment variables
    from dotenv import load_dotenv
    load_dotenv()

    sender = os.environ.get("EMAIL_SENDER")
    password = os.environ.get("EMAIL_PASSWORD")

    # INTERNAL DEBUG - Let's see what the function sees
    print(f"--- Function Internal Check ---")
    print(f"Sender found: {sender}")
    print(f"Password found: {'Yes' if password else 'No'}")

    if not sender or not password:
        return "❌ Error: EMAIL_SENDER or EMAIL_PASSWORD not set in environment."

    # 2. Read the content of the TXT file
    try:
        with open(txt_file_path, 'r', encoding='utf-8') as f:
            body = f.read()
    except Exception as e:
        return f"❌ Error reading TXT file: {e}"

    # 3. Setup the email metadata
    date_str = datetime.now().strftime("%Y-%m-%d")
    subject = f"📊 Market Watch Summary — {date_str}"
    
    msg = MIMEMultipart()
    msg['From'] = f"ING Market Watch <{sender}>"
    msg['To'] = ", ".join(recipients)
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain', 'utf-8'))

    # 4. Send the email
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, recipients, msg.as_string())
        return f"✅ Email successfully sent to: {', '.join(recipients)}"
    except Exception as e:
        return f"❌ SMTP Error: {e}"