import json
from pathlib import Path
from datetime import datetime

def save_classification_summary(json_file_path: str, output_folder: str = "daily_summaries") -> str:
    """
    Reads a classification JSON file and saves a formatted text summary.
    
    Args:
        json_file_path (str): Path to the source JSON file.
        output_folder (str): Folder where the .txt file will be saved.
        
    Returns:
        str: A message indicating success or failure.
    """
    folder = Path(output_folder)
    folder.mkdir(parents=True, exist_ok=True)
    
    try:
        with open(json_file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        return f"Error reading file: {e}"

    date_str = datetime.now().strftime("%Y-%m-%d")
    high, medium, low_count = [], [], 0

    for entry in data.values():
        impact = entry.get("classification", {}).get("impact", "low").lower()
        desc = entry.get("classification", {}).get("description", "No description.")
        
        # Format "Before -> After" for product changes
        field = entry.get("field", "")
        before = entry.get("before", "")
        after = entry.get("after", "")
        
        detail = ""
        if field and before and after and "url" not in field.lower():
            label = field.replace('_', ' ').capitalize()
            detail = f"\n    {label}: {before}  →  {after}"

        item_str = f" • {desc}{detail}"

        if impact == "high":
            high.append(item_str)
        elif impact == "medium":
            medium.append(item_str)
        else:
            low_count += 1

    # Assemble the text content
    content = [
        f"ING Market Watch Summary — {date_str}",
        f"{len(high)} urgent · {len(medium)} to monitor · {low_count} low",
        "-" * 50,
        "\n🔴 REQUIRES ATTENTION"
    ]
    content.extend(high if high else [" • No urgent changes today."])
    content.append("\n🟡 MONITOR")
    content.extend(medium if medium else [" • No items to monitor today."])
    content.extend([
        f"\n🟢 LOW IMPACT: {low_count} minor changes.",
        "\n👉 Full dashboard: https://ing-market-watch.streamlit.app",
        "-" * 50,
        "Generated by ING Market Watch Bot"
    ])

    file_path = folder / f"Summary_{date_str}.txt"
    with open(file_path, "w", encoding="utf-8") as f:
        f.write("\n".join(content))
    
    return f"Success! Summary saved to: {file_path}"