import json
import glob
import os
from pathlib import Path
from datetime import datetime
import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
import pandas as pd

# Update these paths to be safer
BASE_DIR = Path(__file__).resolve().parents[1]
EMAIL_FILE_PATH = BASE_DIR / "data" / "Email" / "team_emails.xlsx"
JSON_OUTPUT_DIR = BASE_DIR / "data" / "outputs"

def get_latest_classified_file(search_dir: str) -> str:
    """
    Finds the most recently created JSON file in the specified directory.
    """
    # Create pattern to look for all .json files in the directory
    pattern = os.path.join(search_dir, "*.json")
    list_of_files = glob.glob(pattern)

    if not list_of_files:
        raise FileNotFoundError(f"No JSON files found in directory: {search_dir}")

    # Return the file with the latest creation/modification time
    return max(list_of_files, key=os.path.getmtime)

def save_classification_summary(json_file_path: str, output_folder: str = "data/daily_summaries") -> str:
    """
    Accurately extracts links and details from the Market Watch JSON.
    """
    folder = Path(output_folder)
    folder.mkdir(parents=True, exist_ok=True)

    try:
        with open(json_file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        return f"Error reading file: {e}"

    date_str = datetime.now().strftime("%Y-%m-%d")
    high, medium, low = [], [], []

    for entry in data.values():
        impact = entry.get("classification", {}).get("impact", "low").lower()
        desc = entry.get("classification", {}).get("description", "No description.")

        # 1. Detail Logic (Before -> After)
        field = entry.get("field", "")
        before = entry.get("before", "")
        after = entry.get("after", "")
        detail = ""

        # Only show transition if it's not a URL field
        if field and before and after and "url" not in field.lower():
            label = field.replace('_', ' ').capitalize()
            detail = f"\n    {label}: {before}  →  {after}"

        # 2. ACCURATE LINK LOGIC
        # Priority: 1. link field, 2. after field (if it's a url), 3. format source as link
        link = entry.get("link")

        # Check if the 'after' value is actually a URL (common for product sheet updates)
        if not link and isinstance(after, str) and after.startswith("http"):
            link = after

        # Check if the source is a full link
        source_val = entry.get("source", "")
        if not link and isinstance(source_val, str) and source_val.startswith("http"):
            link = source_val
        elif not link and source_val:
            # If source is just 'bankshopper.be', make it a link
            link = f"https://www.{source_val}"

        link_line = f"\n    🔗 Link: {link}" if link else ""

        # Combine
        item_str = f" • {desc}{detail}{link_line}"

        if impact == "high":
            high.append(item_str)
        elif impact == "medium":
            medium.append(item_str)
        else:
            low.append(item_str)

    # 3. Assemble Content
    content = [
        f"ING Market Watch Summary — {date_str}",
        f"{len(high)} urgent · {len(medium)} to monitor · {len(low)} low",
        "-" * 50,
        "\n🔴 REQUIRES ATTENTION"
    ]
    content.extend(high if high else [" • No urgent changes today."])
    content.append("\n🟡 MONITOR")
    content.extend(medium if medium else [" • No items to monitor today."])
    content.append("\n🟢 LOW IMPACT / GENERAL UPDATES")
    content.extend(low if low else [" • No minor changes today."])

    content.extend([
        "",
        f"👉 Full dashboard: https://jankazimir-market-watch-agent-streamlitdashboard-0rpbta.streamlit.app/",
        "-" * 50,
        "Generated by ING Market Watch Bot"
    ])

    file_path = folder / f"Summary_{date_str}.txt"
    with open(file_path, "w", encoding="utf-8") as f:
        f.write("\n".join(content))

    return str(file_path)


def send_summary_email(txt_file_path: str, recipients: list[str], sender: str, password: str) -> str:
    """
    RECEIVES sender and password as direct strings.
    """
    # Double check if they arrived empty
    if not sender:
        return "❌ Error: Sender email is empty."
    if not password:
        return "❌ Error: Password is empty."
    """
    Reads a text file and sends its content.
    Credentials are passed directly to avoid environment scope issues.
    """
    if not sender or not password:
        return "❌ Error: Credentials were not passed to the function."

    try:
        with open(txt_file_path, 'r', encoding='utf-8') as f:
            body = f.read()
    except Exception as e:
        return f"❌ Error reading TXT file: {e}"

    # 1. Get credentials from environment variables
    from dotenv import load_dotenv
    load_dotenv()

    sender = os.environ.get("EMAIL_SENDER")
    password = os.environ.get("EMAIL_PASSWORD")

    # INTERNAL DEBUG - Let's see what the function sees
    print(f"--- Function Internal Check ---")
    print(f"Sender found: {sender}")
    print(f"Password found: {'Yes' if password else 'No'}")

    if not sender or not password:
        return "❌ Error: EMAIL_SENDER or EMAIL_PASSWORD not set in environment."

    # 2. Read the content of the TXT file
    try:
        with open(txt_file_path, 'r', encoding='utf-8') as f:
            body = f.read()
    except Exception as e:
        return f"❌ Error reading TXT file: {e}"

    # 3. Setup the email metadata
    date_str = datetime.now().strftime("%Y-%m-%d")
    subject = f"📊 Market Watch Summary — {date_str}"

    msg = MIMEMultipart()
    msg['From'] = f"ING Market Watch <{sender}>"
    msg['To'] = ", ".join(recipients)
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain', 'utf-8'))

    # 4. Send the email
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, recipients, msg.as_string())
        return f"✅ Email successfully sent to: {', '.join(recipients)}"
    except Exception as e:
        return f"❌ SMTP Error: {e}"

# summary_utils.py (Add this to your existing file)



def get_emails_from_excel(file_path: Path) -> list[str]:
    """
    Reads the email list from an Excel file with headers.
    """
    try:
        if not file_path.exists():
            print(f"⚠️ File not found at: {file_path}")
            return []

        # 1. Load the file NORMALLY (Pandas uses the first row as headers by default)
        df = pd.read_excel(file_path)

        # 2. Check if the 'Email' column actually exists to avoid crashing
        if 'email' not in df.columns:
            print("⚠️ Error: Could not find a column named 'Email' in the Excel file.")
            return []

        # 3. Extract the 'Email' column and clean it up
        emails = df['email'].dropna().astype(str).str.strip().tolist()

        # 4. Final safety check (ensure it contains an @ symbol)
        emails = [e for e in emails if "@" in e]

        return emails

    except Exception as e:
        print(f"⚠️ Error reading file: {e}")
        return []

def process_and_send_summary() -> str:
    """
    Master orchestrator: No arguments needed anymore!
    It knows where to find the JSON, the Emails, and the .env.
    """
    # 1. Load Secrets
    env_path = Path(__file__).resolve().parents[1] / ".env"
    load_dotenv(dotenv_path=env_path)

    sender = os.environ.get("EMAIL_SENDER")
    password = os.environ.get("EMAIL_PASSWORD")

    if not sender or not password:
        return "❌ Error: Credentials missing in .env."

    try:
        # 2. Get the list of recipients from Excel
        recipients = get_emails_from_excel(EMAIL_FILE_PATH)
        if not recipients:
            return "❌ Error: No recipients found in Excel."

        # 3. Find newest JSON from our internal config
        latest_json = get_latest_classified_file(JSON_OUTPUT_DIR)

        # 4. Save TXT and get the path
        txt_path = save_classification_summary(latest_json)

        # 5. Send Email
        status = send_summary_email(txt_path, recipients, sender, password)
        return status

    except Exception as e:
        return f"⚠️ Orchestration Error: {str(e)}"